Update deployment configurations for KSP
BCDevOps/allure-framework-openshift pull request #4
Opened 2021-03-03 00:32 UTC by esune

Signed-off-by: Emiliano Suñé <emiliano.sune@gmail.com>

2021-03-03 00:32 UTC, esune commented on openshift/manage
> +    if dcExists "allure-ui"; then
For `allure` there is no `dc` named as the app label, so I picked one of the two components to check whether the app was already deployed.

2021-03-03 00:33 UTC, esune commented
Please note that due to the nature of the service, all traffic between containers is via Internet so the only policies that are necessary are the ones to enable Ingress traffic to the pod(s).

2021-03-04 15:23 UTC, WadeBarnes requested changes
See comment

2021-03-04 15:23 UTC, WadeBarnes commented on openshift/templates/nsp/build.yaml
> +        Disable Aporeto policies: Allow all pods within the namespace to communicate.
`:` in the description will cause the KNP tp be invalid.

2021-03-04 17:54 UTC, WadeBarnes approved these changes

2021-03-04 17:55 UTC, merged